metadata:
  labels:
    global.label.alpha: postgresql
    global.label.beta: postgresql

instances:
- name: ha
  replicas: 1
  dataVolumeClaimSpec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
  metadata:
    labels:
      instance.label.alpha: postgresql
      instance.label.beta: postgresql
      # app.kubernetes.io/name: cannot-override-percona-postgresql
proxy:
  pgBouncer:
    replicas: 1

backups:
  enabled: false

pmm:
  enabled: false
  # secret: cluster1-pmm-secret
  serverHost: monitoring-service.obs
#  querySource: pgstatmonitor
#  customClusterName: "<string>"
#  postgresParams: "<string>"
#  resources:
#    requests:
#      memory: 200M
#      cpu: 500m
